name: CI

on:
  push:
    branches: main
  pull_request:
    branches: "*"

jobs:
  test-contracts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn

      - name: Run Contract Tests
        working-directory: ./
        run: yarn test
